// Turns catalog/pft_phrases.json (the phrase catalog handed over with PFT_Rules_and_Integration.txt) into
// src/engine_1a_catalog.js, a compact constant the engine reads. The JSON stays the source of truth; nothing
// in it is edited by hand here. Sections and sources are kept for the Learn view; notes are kept for the
// phrase browser. Run: node build_catalog.js
const fs = require('fs'), path = require('path');
const src = path.join(__dirname, 'catalog', 'pft_phrases.json');
const cat = JSON.parse(fs.readFileSync(src, 'utf8'));
const ids = new Set();
cat.phrases.forEach(p => { if (ids.has(p.id)) throw new Error('duplicate id ' + p.id); ids.add(p.id); if (!cat.sections[p.section]) throw new Error('unknown section ' + p.section + ' in ' + p.id); });
const phrases = cat.phrases.map(p => {
  const o = { id: p.id, sec: p.section, label: p.label, mode: p.selection_mode, group: p.exclusive_group, fact: p.when.fact, value: p.when.value, t: p.templates, req: {}, src: p.source_ids, notes: p.notes };
  Object.keys(p.required_placeholders || {}).forEach(k => { if (p.required_placeholders[k].length) o.req[k] = p.required_placeholders[k]; });
  // every placeholder in a template must be listed as required for that variant
  Object.keys(p.templates).forEach(k => {
    const used = (p.templates[k].match(/\{([A-Za-z0-9_]+)\}/g) || []).map(x => x.slice(1, -1));
    const listed = (p.required_placeholders && p.required_placeholders[k]) || [];
    used.forEach(u => { if (listed.indexOf(u) < 0) throw new Error(p.id + ' ' + k + ' uses {' + u + '} but does not list it'); });
    listed.forEach(l => { if (used.indexOf(l) < 0) throw new Error(p.id + ' ' + k + ' lists ' + l + ' but does not use it'); });
  });
  return o;
});
const out = { version: cat.catalog_version, reviewed: cat.reviewed_on, title: cat.title, sections: cat.sections, sources: cat.sources, phrases: phrases };
const js = '/* Generated by build_catalog.js from catalog/pft_phrases.json (catalog ' + cat.catalog_version + ', reviewed ' + cat.reviewed_on + '). Do not edit. */\n' +
  'const CATALOG = ' + JSON.stringify(out) + ';\n' +
  'const CAT_BY_ID = {}; CATALOG.phrases.forEach(p => { CAT_BY_ID[p.id] = p; });\n';
fs.writeFileSync(path.join(__dirname, 'src', 'engine_1a_catalog.js'), js);
console.log('engine_1a_catalog.js', js.length, 'bytes,', phrases.length, 'phrases,', Object.keys(cat.sections).length, 'sections,', cat.sources.length, 'sources');
